In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("data/AERO-BirdsEye-Data.csv")  # change filename if different

# Preview
df.head()

,index,NCT,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition
0,0,NCT00003305,Sanofi,A Phase II Trial of Aminopterin in Adults and ...,RATIONALE: Drugs used in chemotherapy use diff...,1997,7,Phase 2,75,Completed,Leukemia
1,1,NCT00003821,Sanofi,Phase II Trial of Aminopterin in Patients With...,RATIONALE: Drugs used in chemotherapy use diff...,1998,1,Phase 2,0,Withdrawn,Endometrial Neoplasms
2,2,NCT00004025,Sanofi,"Phase I/II Trial of the Safety, Immunogenicity...",RATIONALE: Vaccines made from a person's white...,1999,3,Phase 1/Phase 2,36,Unknown status,Melanoma
3,3,NCT00005645,Sanofi,Phase II Trial of ILX295501 Administered Orall...,RATIONALE: Drugs used in chemotherapy use diff...,1999,5,Phase 2,0,Withdrawn,Ovarian Neoplasms
4,4,NCT00008281,Sanofi,"A Multicenter, Open-Label, Randomized, Three-A...",RATIONALE: Drugs used in chemotherapy use diff...,2000,10,Phase 3,0,Unknown status,Colorectal Neoplasms

In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 'app.py',
 'data',
 'feature_columns.pkl',
 'templates',
 'trialytix_model.ipynb',
 'trialytix_model.pkl',
 '__pycache__']

In [3]:
os.listdir("data")

['AERO-BirdsEye-Data.csv']

In [4]:
import pandas as pd
df = pd.read_csv("data/AERO-BirdsEye-Data.csv")
df.head()

,index,NCT,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition
0,0,NCT00003305,Sanofi,A Phase II Trial of Aminopterin in Adults and ...,RATIONALE: Drugs used in chemotherapy use diff...,1997,7,Phase 2,75,Completed,Leukemia
1,1,NCT00003821,Sanofi,Phase II Trial of Aminopterin in Patients With...,RATIONALE: Drugs used in chemotherapy use diff...,1998,1,Phase 2,0,Withdrawn,Endometrial Neoplasms
2,2,NCT00004025,Sanofi,"Phase I/II Trial of the Safety, Immunogenicity...",RATIONALE: Vaccines made from a person's white...,1999,3,Phase 1/Phase 2,36,Unknown status,Melanoma
3,3,NCT00005645,Sanofi,Phase II Trial of ILX295501 Administered Orall...,RATIONALE: Drugs used in chemotherapy use diff...,1999,5,Phase 2,0,Withdrawn,Ovarian Neoplasms
4,4,NCT00008281,Sanofi,"A Multicenter, Open-Label, Randomized, Three-A...",RATIONALE: Drugs used in chemotherapy use diff...,2000,10,Phase 3,0,Unknown status,Colorectal Neoplasms

In [5]:
df = pd.read_csv("data/AERO-BirdsEye-Data.csv")
df.head()

,index,NCT,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition
0,0,NCT00003305,Sanofi,A Phase II Trial of Aminopterin in Adults and ...,RATIONALE: Drugs used in chemotherapy use diff...,1997,7,Phase 2,75,Completed,Leukemia
1,1,NCT00003821,Sanofi,Phase II Trial of Aminopterin in Patients With...,RATIONALE: Drugs used in chemotherapy use diff...,1998,1,Phase 2,0,Withdrawn,Endometrial Neoplasms
2,2,NCT00004025,Sanofi,"Phase I/II Trial of the Safety, Immunogenicity...",RATIONALE: Vaccines made from a person's white...,1999,3,Phase 1/Phase 2,36,Unknown status,Melanoma
3,3,NCT00005645,Sanofi,Phase II Trial of ILX295501 Administered Orall...,RATIONALE: Drugs used in chemotherapy use diff...,1999,5,Phase 2,0,Withdrawn,Ovarian Neoplasms
4,4,NCT00008281,Sanofi,"A Multicenter, Open-Label, Randomized, Three-A...",RATIONALE: Drugs used in chemotherapy use diff...,2000,10,Phase 3,0,Unknown status,Colorectal Neoplasms

In [6]:
import os
os.listdir("data")

['AERO-BirdsEye-Data.csv']

In [7]:
df = pd.read_csv("data/AERO-BirdsEye-Data.csv")
df.head()

,index,NCT,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition
0,0,NCT00003305,Sanofi,A Phase II Trial of Aminopterin in Adults and ...,RATIONALE: Drugs used in chemotherapy use diff...,1997,7,Phase 2,75,Completed,Leukemia
1,1,NCT00003821,Sanofi,Phase II Trial of Aminopterin in Patients With...,RATIONALE: Drugs used in chemotherapy use diff...,1998,1,Phase 2,0,Withdrawn,Endometrial Neoplasms
2,2,NCT00004025,Sanofi,"Phase I/II Trial of the Safety, Immunogenicity...",RATIONALE: Vaccines made from a person's white...,1999,3,Phase 1/Phase 2,36,Unknown status,Melanoma
3,3,NCT00005645,Sanofi,Phase II Trial of ILX295501 Administered Orall...,RATIONALE: Drugs used in chemotherapy use diff...,1999,5,Phase 2,0,Withdrawn,Ovarian Neoplasms
4,4,NCT00008281,Sanofi,"A Multicenter, Open-Label, Randomized, Three-A...",RATIONALE: Drugs used in chemotherapy use diff...,2000,10,Phase 3,0,Unknown status,Colorectal Neoplasms

In [8]:
df = pd.read_csv("data/AERO-BirdsEye-Data.csv")
df.head()

,index,NCT,Sponsor,Title,Summary,Start_Year,Start_Month,Phase,Enrollment,Status,Condition
0,0,NCT00003305,Sanofi,A Phase II Trial of Aminopterin in Adults and ...,RATIONALE: Drugs used in chemotherapy use diff...,1997,7,Phase 2,75,Completed,Leukemia
1,1,NCT00003821,Sanofi,Phase II Trial of Aminopterin in Patients With...,RATIONALE: Drugs used in chemotherapy use diff...,1998,1,Phase 2,0,Withdrawn,Endometrial Neoplasms
2,2,NCT00004025,Sanofi,"Phase I/II Trial of the Safety, Immunogenicity...",RATIONALE: Vaccines made from a person's white...,1999,3,Phase 1/Phase 2,36,Unknown status,Melanoma
3,3,NCT00005645,Sanofi,Phase II Trial of ILX295501 Administered Orall...,RATIONALE: Drugs used in chemotherapy use diff...,1999,5,Phase 2,0,Withdrawn,Ovarian Neoplasms
4,4,NCT00008281,Sanofi,"A Multicenter, Open-Label, Randomized, Three-A...",RATIONALE: Drugs used in chemotherapy use diff...,2000,10,Phase 3,0,Unknown status,Colorectal Neoplasms

In [9]:
df["Status"].value_counts()

Status
Completed                  10568
Terminated                  1285
Recruiting                   800
Active, not recruiting       646
Withdrawn                    291
Not yet recruiting           108
Unknown status                19
Suspended                     16
Enrolling by invitation       15
Name: count, dtype: int64

In [10]:
# Keep only completed and failed trials
df_filtered = df[df["Status"].isin(["Completed", "Terminated", "Withdrawn", "Suspended"])]

# Create binary target variable
df_filtered["Success"] = df_filtered["Status"].apply(
    lambda x: 1 if x == "Completed" else 0
)

# Check new distribution
df_filtered["Success"].value_counts()

C:\Users\admin\AppData\Local\Temp\ipykernel_6128\2110755526.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["Success"] = df_filtered["Status"].apply(

Success
1    10568
0     1592
Name: count, dtype: int64

In [11]:
df_filtered["Success"].value_counts()

Success
1    10568
0     1592
Name: count, dtype: int64

In [12]:
# Select relevant columns
features = ["Phase", "Enrollment", "Start_Year", "Sponsor", "Condition"]

X = df_filtered[features]
y = df_filtered["Success"]

X.head()

     Phase  Enrollment  Start_Year Sponsor                       Condition
0  Phase 2          75        1997  Sanofi                        Leukemia
1  Phase 2           0        1998  Sanofi           Endometrial Neoplasms
3  Phase 2           0        1999  Sanofi               Ovarian Neoplasms
6  Phase 3           0        2000  Sanofi            Colorectal Neoplasms
7  Phase 3           0        2000  Sanofi  Carcinoma, Non-Small-Cell Lung

In [13]:
X["Enrollment"].describe()

count    12160.000000
mean       428.913405
std       1897.333199
min          0.000000
25%         37.000000
50%        118.000000
75%        355.000000
max      84496.000000
Name: Enrollment, dtype: float64

In [14]:
# One-hot encode categorical features
X_encoded = pd.get_dummies(X, columns=["Phase", "Sponsor", "Condition"], drop_first=True)

X_encoded.head()

,Enrollment,Start_Year,Phase_Phase 1,Phase_Phase 1/Phase 2,Phase_Phase 2,Phase_Phase 2/Phase 3,Phase_Phase 3,Phase_Phase 4,Sponsor_Bayer,Sponsor_GSK,...,Condition_Warts,Condition_Weight Loss,Condition_West Nile Fever,Condition_Wet Macular Degeneration,Condition_Whooping Cough,Condition_Wound Infection,Condition_Wounds and Injuries,Condition_Xerostomia,Condition_Yellow Fever,Condition_beta-Thalassemia
0,75,1997,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0,1998,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,1999,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,0,2000,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,0,2000,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
X_encoded.shape

(12160, 839)

In [16]:
from sklearn.model_selection import train_test_split

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, 
    test_size=0.2, 
    random_state=42,
    stratify=y  # very important for imbalance
)

X_train.shape, X_test.shape

((9728, 839), (2432, 839))

In [17]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [18]:
from sklearn.metrics import classification_report, roc_auc_score

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))

              precision    recall  f1-score   support

           0       0.70      0.35      0.47       318
           1       0.91      0.98      0.94      2114

    accuracy                           0.90      2432
   macro avg       0.81      0.66      0.70      2432
weighted avg       0.88      0.90      0.88      2432

ROC-AUC: 0.8459357502841197

In [19]:
import pandas as pd

# Get feature importance
importances = pd.Series(model.feature_importances_, index=X_encoded.columns)

# Top 10 important features
top_features = importances.sort_values(ascending=False).head(10)

top_features

Enrollment                             0.307167
Start_Year                             0.129692
Sponsor_Pfizer                         0.014778
Phase_Phase 2                          0.013263
Phase_Phase 3                          0.011848
Phase_Phase 1                          0.011249
Sponsor_Merck                          0.011094
Sponsor_Novartis                       0.010688
Sponsor_GSK                            0.010539
Condition_Diabetes Mellitus, Type 2    0.010265
dtype: float64

In [20]:
# Example: take first test sample
sample = X_test.iloc[0:1]

pred_prob = model.predict_proba(sample)[0][1]

print("Predicted Success Probability:", round(pred_prob * 100, 2), "%")

Predicted Success Probability: 94.0 %

In [21]:
import joblib

joblib.dump(model, "trialytix_model.pkl")
joblib.dump(X_encoded.columns.tolist(), "feature_columns.pkl")

['feature_columns.pkl']

In [23]:
import joblib

joblib.dump(model, "trialytix_model.joblib")
joblib.dump(X_encoded.columns, "feature_columns.joblib")

['feature_columns.joblib']